FROM python:3.12

WORKDIR /workspace

RUN apt-get update && apt-get install -y --no-install-recommends \
  libgl1 \
  libglib2.0-0 \
  libxcb1 \
  && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
  "rfdetr[onnxexport]==1.5.0"

CMD ["bash"]
